/**
 * RFC Store — Invoice Numbering
 * 
 * Gets or creates the invoice record for an order.
 * Invoice data is an immutable JSONB snapshot set at first generation.
 * Subsequent calls return the existing record (historical accuracy).
 *
 * Server-side only (uses admin client) — do not import in client components.
 */

import { createAdminClient } from '@/lib/supabase/admin';
import type { Json } from '@/types/database';
import type { InvoiceData } from './types';

export interface InvoiceRecord {
  invoiceNumber: string;
  issuedAt: string;
  invoiceData: InvoiceData;
}

/**
 * Gets or creates the invoice for an order.
 * If invoice already exists, returns stored snapshot (immutable).
 * If not, creates a new invoice with the provided data snapshot.
 */
export async function getOrCreateInvoice(
  orderId: string,
  invoiceData: InvoiceData
): Promise<InvoiceRecord> {
  const admin = createAdminClient();

  // Check if already exists
  const { data: existing } = await admin
    .from('invoices')
    .select('invoice_number, issued_at, invoice_data')
    .eq('order_id', orderId)
    .maybeSingle();

  if (existing) {
    return {
      invoiceNumber: existing.invoice_number,
      issuedAt: existing.issued_at,
      invoiceData: existing.invoice_data as unknown as InvoiceData,
    };
  }

  // Create new invoice record (invoice_number auto-generated by DB sequence)
  const { data: created, error } = await admin
    .from('invoices')
    .insert({
      order_id: orderId,
      invoice_data: invoiceData as unknown as Json,
    })
    .select('invoice_number, issued_at, invoice_data')
    .single();

  if (error || !created) {
    // Handle race condition: another request created the invoice simultaneously
    const { data: retry } = await admin
      .from('invoices')
      .select('invoice_number, issued_at, invoice_data')
      .eq('order_id', orderId)
      .single();
    if (!retry) throw new Error('Failed to create invoice record');
    return {
      invoiceNumber: retry.invoice_number,
      issuedAt: retry.issued_at,
      invoiceData: retry.invoice_data as unknown as InvoiceData,
    };
  }

  return {
    invoiceNumber: created.invoice_number,
    issuedAt: created.issued_at,
    invoiceData: created.invoice_data as unknown as InvoiceData,
  };
}
